service: sls-test-project

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2

  memorySize: 512
  timeout: 15

  stackTags: # Optional CF stack tags
    environment: ${opt:stage, self:provider.stage}
    application: ${self:service}
    product: something

  environment:
    SERVERLESS_PROJECT_NAME: ${self:service} # FIXME Required for Sessions
    SERVERLESS_PROJECT: ${self:service}
    SERVERLESS_STAGE: ${self:custom.stage}
    SERVERLESS_REGION: ${self:custom.region}

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-aws-alias

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

  # Stage dependent variables.
  # Usage: ${self:custom.${self:custom.stage}.<varname>}
  dev:
    testvar: test-${self:custom.stage}

  prod:
    testvar: test-${self:custom.stage}

  webpack: ./webpack.lambda.config.js
  webpackIncludeModules: true

functions:
  testfct1:
    description: 'build: ${env:DEPLOY_TAG}'
    handler: handlers/testfct1/handler.handle
    events:
      - http:
          path: fct1
          method: get
          cors: true